name: CI Pipeline

on: [push]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16

    - name: Install dependencies
      run: npm ci
      working-directory: nextv3

    - name: Build project
      run: npm run build
      working-directory: nextv3

    - name: Run Playwright tests
      run: npm run test-playwright
      working-directory: nextv3

  deploy:
    runs-on: ubuntu-latest
    needs: build_and_test

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16

    - name: Install dependencies
      run: npm ci
      working-directory: nextv3

    - name: Build project
      run: npm run build
      working-directory: nextv3

    - name: Deploy to Netlify
      uses: netlify/actions/cli@master
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
      with:
        args: deploy --prod
        working-directory: nextv3

  retest_deployed_app:
    runs-on: ubuntu-latest
    needs: deploy

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16

    - name: Install dependencies
      run: npm ci
      working-directory: nextv3

    - name: Run Playwright tests on deployed app
      run: npm run test-playwright
      working-directory: nextv3
      env:
        BASE_URL: ${{ secrets.DEPLOYED_APP_URL }}
